import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Table',
  description: 'Generated by create next app'
};
export default function Page() {
  type TableRow = {
    id: number;
    content: string[];
  };

  const totalColumn = 20;

  const data: TableRow[] = Array.from({ length: 50 }, (_, i) => ({
    id: i + 1,
    content: Array(totalColumn).fill(`Content ${i + 1}`)
  }));
  return (
    <div className="min-h-[100vh] flex-1 rounded-xl md:min-h-min">
      <div className="relative overflow-hidden">
        <div className="!important relative h-[calc(100vh-500px)] w-full overflow-auto bg-blue-50 dark:bg-blue-950">
          <table className="!important w-full border-collapse">
            <thead>
              <tr>
                {Array.from({ length: totalColumn }, (_, i) => (
                  <th
                    key={i}
                    className={`text-nowrap border bg-gray-800 p-2 text-white ${
                      i === 0 ? 'sticky left-0 bg-gray-500' : ''
                    } sticky top-0 z-10`}
                  >
                    Header {i + 1}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.map((row) => (
                <tr key={row.id}>
                  {row.content.map((content, i) => (
                    <td
                      key={i}
                      className={`text-nowrap border bg-gray-100 p-2 dark:bg-gray-700 ${i === 0 ? 'sticky left-0' : ''}`}
                    >
                      {content}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
